/* 자동 생성 — 직접 수정하지 말 것.
 *
 * 생성: python scripts/gen_from_xlsx.py
 * 출처: 반도체 불량 분석 개선안.xlsx · 불량 대응 log.xlsx (둘 다 읽기 전용 원본)
 * 생성 시각: 2026-08-14 17:25
 *
 * 엑셀이 소스 오브 트루스다. 내용이 잘못됐으면 이 파일이 아니라 엑셀을 고치고
 * 스크립트를 다시 돌린다.
 */
import type { CauseEntry, ExclusionNote } from './causes';

/** 대장의 집계 마감일 = 마지막 발생일. 상태 판정의 기준점 (domain/caseStatus.ts) */
export const LOG_CUTOFF = '2026-08-05';

export const CAUSE_MATRIX: CauseEntry[] = [
  {
    id: 'diffusion-donut-1',
    process: 'DIFFUSION',
    pattern: 'Donut',
    variant: 1,
    name: 'Gas Injector 농도 구배 편차로 인한 Doping Profile 불량',
    mechanism: [
      '챔버 내부에 반응 가스를 공급하는 Injector 배치 문제로 인해, 중심에서 Edge 영역으로 퍼지는 반응 가스의 Concentration Gradient에 굴곡이 발생',
      '특정 반경대에서만 반응 가스가 짙거나 옅게 맴돌며 Doping Concentration의 편차를 유발',
      '가스 농도가 높았던 반경대는 도핑 과다로 Sheet Resistance(Rs)가 낮게, 농도가 낮았던 반경대는 Doping 부족으로 Sheet Resistance(Rs)가 높게 측정',
      '이후 열처리를 진행 시 낮았던 부분은 Dopant 확산에 의해 어느정도 회복되고, 높았던 부분에 주로 문제 발생',
    ],
    waferMap: 'Doping Concentration에 이상이 발생한 특정 반경대의 Sheet Resistance(Rs)가 Spec보다 작아서 불량으로 분류된 형태',
    resolution: [
      'Inner/Outer Tube 점검',
      'Sheet Resistance(Rs) 이탈 반경대 재계측으로 Spec 이탈 범위 확정',
    ],
    improvement: [
      'CFD 시뮬레이션을 통한 인젝터 배치 재설계',
      'Turn Table 회전속도 최적화',
    ],
    logIds: [
      'WD-001',
    ],
    occurrences: 3,
    metrology: '4-Point Probe',
    lastSeen: '2025-10-29',
    openCase: false,
  },
  {
    id: 'diffusion-edgering-1',
    process: 'DIFFUSION',
    pattern: 'Edge-Ring',
    variant: 1,
    name: 'Furnace Edge Zone 온도 Calibration 오차로 인한 반경방향 온도구배 불량',
    mechanism: [
      'Zone별 T/C 5~7개로 온도를 관리하는데 Edge Zone Calibration이 어긋나면 웨이퍼 Edge 영역 전체가 목표 확산 정도에서 오차 발생',
      'Edge 영역 온도가 낮았던 경우 확산 부족으로 Sheet Resistance(Rs)가 Spec보다 높게, 높았던 경우 확산 과다로 Sheet Resistance(Rs)가 Spec보다 낮게 측정되는 불량 발생',
    ],
    waferMap: 'Edge 영역 전체의 Sheet Resistance(Rs)가 Spec을 벗어나 불량으로 분류된 형태',
    resolution: [
      'Flat Zone 온도 Re-Calibration',
      'Edge 영역 Sheet Resistance(Rs) 재계측으로 정상화 확인',
    ],
    improvement: [
      'Zone별 온도 독립제어 시스템 강화',
      'T/C PM 주기 준수 강화',
    ],
    logIds: [
      'WD-002',
    ],
    occurrences: 4,
    metrology: '4-Point Probe',
    lastSeen: '2025-12-08',
    openCase: false,
  },
  {
    id: 'diffusion-edgeloc-1',
    process: 'DIFFUSION',
    pattern: 'Edge-Loc',
    variant: 1,
    name: 'Cap 개폐 시 유입 Particle 불량',
    mechanism: [
      'Tube 개폐구인 Cap은 챔버 내 특정 방향에 고정되어 있음',
      'Cap 개폐 시 발생하는 기류나 마찰로 인해 유입된 Particle이 항상 Cap과 가장 가까운 방향의 웨이퍼 Edge 영역에 국소적으로 부착',
    ],
    waferMap: 'Edge 영역 중 Cap 위치와 가까운 특정 방향 국소 부위에 Particle 등의 Defect Count가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      'Cap 인접 웨이퍼 우선 Particle 검사',
      'O-ring 교체',
    ],
    improvement: [
      'Cap 개폐 시 N2 Purge 강화',
    ],
    logIds: [
      'WD-003',
    ],
    occurrences: 5,
    metrology: 'DF Inspection',
    lastSeen: '2026-01-17',
    openCase: false,
    directional: {
      kind: 'fixed',
      clock: 9,
      label: '9시 방향',
    },
  },
  {
    id: 'diffusion-loc-1',
    process: 'DIFFUSION',
    pattern: 'Loc',
    variant: 1,
    name: 'Quartz Tube/Boat 누적막 Crack으로 발생한 Particle 불량',
    mechanism: [
      'PM 주기 미준수 시 Quartz Tube나 Boat의 누적막에 Crack이 생겨 Particle이 국소적으로 낙하',
      '낙하 위치를 예측할 수 없어 반복성 없이 임의 위치에 집중되어 Particle 불량 발생',
    ],
    waferMap: '국소 영역에 Particle 등의 Defect Count가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      'Crack 발생 Tube/Boat 즉시 사용 중단',
      '동일 Batch Lot Particle 재검사',
    ],
    improvement: [
      'Tube 내 In-situ Particle Monitor 도입 검토',
      'PM 주기 단축',
    ],
    logIds: [
      'WD-004A',
      'WD-004B',
    ],
    occurrences: 6,
    metrology: 'DF Inspection',
    lastSeen: '2025-11-15',
    openCase: false,
  },
  {
    id: 'diffusion-random-1',
    process: 'DIFFUSION',
    pattern: 'Random',
    variant: 1,
    name: 'Tube 및 Ambient 오염으로 인한 Particle 불량',
    mechanism: [
      'FOUP→TM→Chamber 이송 경로 전반의 Ambient 오염 존재',
      '무작위하게 Particle 불량이 발생',
    ],
    waferMap: '무작위한 영역에서 Particle 등의 Defect Count가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      '무작위 Particle Count 초과 Lot 이송경로 오염원 점검 후 재검사',
    ],
    improvement: [
      'Loadlock/FOUP Loader Purge 최적화',
    ],
    logIds: [
      'WD-005A',
      'WD-005B',
    ],
    occurrences: 6,
    metrology: 'DF Inspection',
    lastSeen: '2025-11-20',
    openCase: false,
  },
  {
    id: 'diffusion-scratch-1',
    process: 'DIFFUSION',
    pattern: 'Scratch',
    variant: 1,
    name: 'Boat Slot 삽입 마찰로 인한 Scratch 불량',
    mechanism: [
      'Horizontal Boat Slot 구조상 Loading/Un-Loading 시 웨이퍼 Edge 영역에 접촉 발생',
      '삽입 마찰이 임의 위치에서 발생하면서 방향성 없는 선형 Scratch 불량 발생',
    ],
    waferMap: '임의 방향의 선형 Scratch가 Defect Count로 검출되어 불량으로 분류된 형태',
    resolution: [
      'Slot 마모 확인 후 이상 시 교체',
      'Scratch Defect Count 전수 재검사로 심각도 판정',
    ],
    improvement: [
      'Boat 슬롯 저마찰 소재/코팅 적용',
      'Slot 마모 정기 점검 강화',
    ],
    logIds: [
      'WD-006',
    ],
    occurrences: 5,
    metrology: 'DF Inspection',
    lastSeen: '2026-02-02',
    openCase: false,
  },
  {
    id: 'diffusion-nearfull-1',
    process: 'DIFFUSION',
    pattern: 'Near-full',
    variant: 1,
    name: 'Torch(H2/O2) 반응 실패로 인한 전면 산화 미형성 불량',
    mechanism: [
      'Wet Oxidation용 Torch 점화에 실패하면 산화 자체가 웨이퍼 전면에서 일어나지 않음',
      'Oxide Thickness(Tox)가 Spec 대비 0에 가깝게 측정되는 산화막 미형성 불량 발생',
    ],
    waferMap: '전체 영역의 Oxide Thickness(Tox)가 Spec보다 작아서 불량으로 분류된 형태',
    resolution: [
      'H2/O2 Ratio 점검',
      'Igniter 이상 확인 및 교체',
      '미산화 Lot Oxide Thickness(Tox) 전수 재계측',
    ],
    improvement: [
      'Torch 점화 안정성 실시간 모니터링 강화',
    ],
    logIds: [
      'WD-007',
    ],
    occurrences: 3,
    metrology: 'Ellipsometry/OCD',
    lastSeen: '2025-11-29',
    openCase: false,
  },
  {
    id: 'diffusion-edgering-2',
    process: 'DIFFUSION',
    pattern: 'Edge-Ring',
    variant: 2,
    name: 'Gas Depletion Effect으로 인한 Edge Doping 불량',
    mechanism: [
      'Inner/Outer Tube 이중구조에서 반응 가스가 Boat 전면을 통과하며 소모되어, 벽에 가까운 Edge 영역일수록 반응물 농도가 낮아짐',
      '반응물이 부족한 Edge 영역의 Doping Concentration이 낮아져 Sheet Resistance(Rs)가 Spec보다 높게 측정되는 불량 발생',
    ],
    waferMap: 'Edge 영역 전체의 Sheet Resistance(Rs)가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      'Edge 영역 Sheet Resistance(Rs) 이탈 Lot Gas Flow·Boat Rotation 실측 점검',
    ],
    improvement: [
      'Gas Injector 위치·각도 CFD 기반 재설계',
      'Boat Rotation 속도 최적화',
      'Ring Boat 채택 검토',
    ],
    logIds: [
      'WD-008',
    ],
    occurrences: 4,
    metrology: '4-Point Probe',
    lastSeen: '2026-01-08',
    openCase: false,
  },
  {
    id: 'diffusion-edgeloc-2',
    process: 'DIFFUSION',
    pattern: 'Edge-Loc',
    variant: 2,
    name: 'Boat Slot 지지 핀 고정 접촉점으로 인한 방향성 Particle 불량',
    mechanism: [
      'Notch를 동일 각도로 정렬해 로딩하면 Boat Slot의 지지 핀이 매번 같은 위치에 접촉함',
      '노치 기준으로 고정 방향에서 Particle 부착이 여러 웨이퍼에 걸쳐 반복 발생하는 불량',
    ],
    waferMap: 'Edge 영역 중 특정 방향 국소 부위에 Particle 등의 Defect Count가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      'Boat Slot 접촉면 Wet Clean',
      '동일 방향 반복 검출 Lot 재검사',
    ],
    improvement: [
      '지지 핀 위치의 오염 집중 모니터링',
    ],
    logIds: [
      'WD-009',
    ],
    occurrences: 5,
    metrology: 'DF Inspection',
    lastSeen: '2026-02-17',
    openCase: false,
    directional: {
      kind: 'fixed',
      clock: 6,
      label: '6시 방향',
    },
  },
  {
    id: 'diffusion-loc-2',
    process: 'DIFFUSION',
    pattern: 'Loc',
    variant: 2,
    name: 'Tube 내부 돌출 구조물로 인한 방향성 Particle 불량',
    mechanism: [
      'Boat 회전이 불완전하거나 정지 구간이 있으면 T/C·Gas Injector 등 돌출 구조물에 가장 가까운 방향에 Particle이 국소적으로 낙하',
      '완전 회전 중에는 도넛형으로 퍼지지만, 정지 구간이 있으면 고정된 방향에 결함이 반복됨',
    ],
    waferMap: '돌출 구조물 인접 국소 영역에 Particle 등의 Defect Count가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      'T/C·Injector 표면 Particle 발생원 점검 및 세정',
    ],
    improvement: [
      '회전 프로파일 재검토를 통한 정지 구간 최소화',
    ],
    logIds: [
      'WD-010',
    ],
    occurrences: 4,
    metrology: 'DF Inspection',
    lastSeen: '2026-01-18',
    openCase: false,
    directional: {
      kind: 'layout',
      label: '장비 구조 의존',
    },
  },
  {
    id: 'diffusion-scratch-2',
    process: 'DIFFUSION',
    pattern: 'Scratch',
    variant: 2,
    name: 'Boat Transfer Robot ARM 진입 방향 접촉으로 인한 방향성 Scratch 불량',
    mechanism: [
      'Transfer Robot의 End Effector는 설정된 동선에 따라 항상 동일한 방향과 각도로 웨이퍼를 픽업 및 삽입 진행',
      'ARM의 진입 각도 및 Grip force 이상으로 웨이퍼를 픽업 및 삽입할 때 접촉 마찰이 동일한 위치에 발생하는 불량 발생',
    ],
    waferMap: '특정 위치에 고정적으로 나타나는 선형 Scratch가 Defect Count로 검출되어 불량으로 분류된 형태',
    resolution: [
      'Scratch 검출 위치의 Robot ARM 진입 각도 및 Grip force를 Dummy Wafer로 점검',
    ],
    improvement: [
      'Robot ARM 진입 각도·Grip Force 정기 점검 주기 수립',
    ],
    logIds: [
      'WD-011',
    ],
    occurrences: 5,
    metrology: 'DF Inspection',
    lastSeen: '2026-02-27',
    openCase: false,
    directional: {
      kind: 'fixed',
      clock: 3,
      label: '3시 방향',
    },
  },
  {
    id: 'deposition-center-1',
    process: 'DEPOSITION',
    pattern: 'Center',
    variant: 1,
    name: 'RF Power Standing Wave Effect으로 인한 Over-Deposition 불량',
    mechanism: [
      'PECVD 챔버의 크기와 인가된 RF 주파수의 파장이 맞물리며 Electric Field가 챔버 중앙으로 모이는 Standing Wave 발생',
      '웨이퍼 중앙부근에 Plasma Density가 높게 형성됨',
      '반응성 이온과 라디칼이 중심에 집중되어 중심부 박막 두께(THK)가 Spec을 초과하여 지나치게 두꺼워지는 Over-Deposition 불량',
    ],
    waferMap: '중심부의 박막 두께 (THK)가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      '박막 두께(THK) 중심부 Spec 초과 Lot 격리 후 전후 공정 이력 확인',
      '동일 챔버 후속 Lot 진행 여부 판단',
    ],
    improvement: [
      'Electric Field 분산을 위한 RF Matcher 튜닝',
      '하드웨어 구조를 고려해 공정 주파수 재설정',
    ],
    logIds: [
      'WD-012',
    ],
    occurrences: 4,
    metrology: 'Ellipsometry/OCD',
    lastSeen: '2026-01-28',
    openCase: false,
  },
  {
    id: 'deposition-donut-1',
    process: 'DEPOSITION',
    pattern: 'Donut',
    variant: 1,
    name: 'PVD Target 마모로 인한 Sputter Flux 불균일 불량',
    mechanism: [
      'Magnetron Sputtering 공정 중 자기장에 의해 Target의 특정 반경대만 집중적으로 깎여나가는 마모 현상 발생',
      '마모 초기에는 해당 반경대의 Sputter Flux가 증가하고, 마모 지속되는 경우 말기에는 Sputter Flux가 감소',
      'Sputter Flux가 높을 때는 박막 두께(THK)가 Spec을 초과하고, 낮을 때에는 박막 두께(THK)가 Spec보다 작은 불량 발생',
    ],
    waferMap: 'Sputter Flux가 비정상적인 특정 반경대의 박막 두께(THK)가 Spec을 벗어나 불량으로 분류된 형태',
    resolution: [
      'Target 사용시간 및 마모 정도 확인 후 이상시 Target 교체',
      '박막 두께(THK) 이탈 반경대 재계측으로 Spec 이탈 범위 확정',
    ],
    improvement: [
      'Target-Wafer 거리 최적화',
    ],
    logIds: [
      'WD-013',
    ],
    occurrences: 4,
    metrology: 'Ellipsometry/OCD',
    lastSeen: '2026-02-02',
    openCase: false,
  },
  {
    id: 'deposition-edgering-1',
    process: 'DEPOSITION',
    pattern: 'Edge-Ring',
    variant: 1,
    name: '챔버 배기구 인접부분 가스 고갈로 인한 Under-Deposition 불량',
    mechanism: [
      '챔버 배기구가 Edge 영역에 위치한 구조 탓에, 반응 가스가 중심에서 Edge 영역으로 흐르면서 점차 고갈됨',
      'Edge 영역 영역에 도달할 반응 물질이 부족해지면서 테두리 부위의 두께(THK)가 기준 스펙보다 얇게 형성됨',
      'Egde 영역 전체에 가스 부족으로 인해 박막 두께(THK)가 Spec보다 얇게 증착되는 Under-Deposition 불량',
    ],
    waferMap: 'Edge 영역 전체의 박막 두께 (THK)가 Spec보다 작아서 불량으로 분류된 형태',
    resolution: [
      'Edge 영역 박막 두께(THK) Spec 미달 확인 시 해당 Lot 격리 후 배기구·Pump 압력 실측값 기록 확인',
    ],
    improvement: [
      '배기구 위치 및 Pump 압력 재설정',
      'Gas Injector 재설계',
    ],
    logIds: [
      'WD-014',
    ],
    occurrences: 4,
    metrology: 'Ellipsometry/OCD',
    lastSeen: '2026-02-07',
    openCase: false,
  },
  {
    id: 'deposition-edgeloc-1',
    process: 'DEPOSITION',
    pattern: 'Edge-Loc',
    variant: 1,
    name: '챔버 내벽 누적막 탈피로 인한 Particle 불량',
    mechanism: [
      '챔버 내벽에 누적되어 있던 폴리머나 증착 부산물이 한계치에 도달해 탈락하면서 Particle이 떨어짐',
      '챔버가 웨이퍼를 감싸고 있는 형태라 내벽에 가까운 웨이퍼 Edge 영역 중 국소 부위에 집중적으로 Particle 발생',
    ],
    waferMap: 'Edge 영역 중 국소 부위에 Particle 등의 Defect Count가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      '챔버 Cleaning 진행',
    ],
    improvement: [
      'RPS를 활용한 In-situ Clean 주기 관리 강화',
    ],
    logIds: [
      'WD-015',
    ],
    occurrences: 4,
    metrology: 'DF Inspection',
    lastSeen: '2026-02-12',
    openCase: false,
  },
  {
    id: 'deposition-loc-1',
    process: 'DEPOSITION',
    pattern: 'Loc',
    variant: 1,
    name: 'PECVD Showerhead 특정 부분 구멍 막힘으로 인한 Under-Deposition 불량',
    mechanism: [
      'PECVD Showerhead의 특정 부분 미세 구멍들이 부산물로 막힘',
      '웨이퍼 국소 영역으로 공급되는 반응 가스의 절대적인 양이 부족해짐',
      '가스 부족으로 인해 국소 영역의 증착률이 떨어져, 국소 영역의 박막 두께(THK)가 Spec보다 얇게 증착되는 Under-Deposition 불량',
    ],
    waferMap: '국소 영역의 박막 두께 (THK)가 Spec보다 작아서 불량으로 분류된 형태',
    resolution: [
      'Showerhead 미세 구멍별 가스 유량 점검',
      '막힘 부위 확인 시 부품 교체',
      '국소 박막 두께(THK) 재계측으로 Spec 이탈 범위 확정',
    ],
    improvement: [
      'Showerhead 정기 교체·세정 주기 수립',
    ],
    logIds: [
      'WD-016',
    ],
    occurrences: 4,
    metrology: 'Ellipsometry/OCD',
    lastSeen: '2026-02-18',
    openCase: false,
  },
  {
    id: 'deposition-random-1',
    process: 'DEPOSITION',
    pattern: 'Random',
    variant: 1,
    name: 'Chamber 및 TM Ambient 오염으로 인한 Particle 불량',
    mechanism: [
      'FOUP→TM→Chamber 이송 경로 전반의 Ambient 오염 존재',
      '무작위하게 Particle 불량이 발생',
    ],
    waferMap: '무작위한 영역에서 Particle 등의 Defect Count가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      '무작위 Particle Count 초과 Lot Wet Clean 진행 후 재검사',
      'TM 진공도 실측 확인',
    ],
    improvement: [
      'TM Vacuum 관리',
      'Load Lock Purge 최적화',
    ],
    logIds: [
      'WD-017A',
      'WD-017B',
    ],
    occurrences: 6,
    metrology: 'DF Inspection',
    lastSeen: '2026-01-21',
    openCase: false,
  },
  {
    id: 'deposition-scratch-1',
    process: 'DEPOSITION',
    pattern: 'Scratch',
    variant: 1,
    name: 'Boat Slot 삽입 마찰로 인한 Scratch 불량',
    mechanism: [
      'Horizontal Boat Slot 구조상 Loading/Un-Loading 시 웨이퍼와 접촉이 발생',
      '삽입 마찰이 임의 위치에서 발생하면서 방향성 없는 선형 Scratch 불량 발생',
    ],
    waferMap: '임의 방향의 선형 Scratch가 Defect Count로 검출되어 불량으로 분류된 형태',
    resolution: [
      'Slot 마모 확인 후 이상 시 교체',
      'Scratch Defect Count 전수 재검사로 심각도 판정',
    ],
    improvement: [
      'Boat 슬롯 저마찰 소재/코팅 적용',
      'Slot 마모 정기 점검 강화',
    ],
    logIds: [
      'WD-018',
    ],
    occurrences: 4,
    metrology: 'DF Inspection',
    lastSeen: '2026-02-28',
    openCase: false,
  },
  {
    id: 'deposition-nearfull-1',
    process: 'DEPOSITION',
    pattern: 'Near-full',
    variant: 1,
    name: '챔버 내벽 누적막 탈피로 인한 대량 Particle 불량',
    mechanism: [
      'PM 주기, RPS Clean 주기를 지키지 않아 챔버 내벽에 한계치 이상으로 증착막이 두껍게 누적',
      '자체 응력으로 인해 탈락하면서 대량의 Particle이 떨어져 불량 발생',
    ],
    waferMap: '전체 영역에 걸쳐 Particle 등의 Defect Count가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      '챔버 Cleaning 진행',
      '전면 Particle Count 급증 Lot 전량 격리 후 전수검사',
    ],
    improvement: [
      'PM 및 RPS Clean 주기 관리 강화',
    ],
    logIds: [
      'WD-019',
    ],
    occurrences: 3,
    metrology: 'DF Inspection',
    lastSeen: '2026-01-29',
    openCase: false,
  },
  {
    id: 'deposition-center-2',
    process: 'DEPOSITION',
    pattern: 'Center',
    variant: 2,
    name: 'PECVD Showerhead 중심부 막힘으로 인한 Under-Deposition 불량',
    mechanism: [
      'PECVD Showerhead의 중심부 미세 구멍들이 부산물로 막힘',
      '웨이퍼 중심부로 공급되는 반응 가스의 절대적인 양이 부족해짐',
      '가스 부족으로 인해 중심부의 증착률이 떨어져, 중심부 박막 두께(THK)가 Spec보다 얇게 증착되는 Under-Deposition 불량',
    ],
    waferMap: '중심부의 박막 두께 (THK)가 Spec보다 작아서 불량으로 분류된 형태',
    resolution: [
      'Showerhead 이물질 확인 후 Cleaning 혹은 부품 교체 진행',
      '중심부 박막 두께(THK) 재계측으로 정상화 확인',
    ],
    improvement: [
      'Showerhead 정기 교체·세정 주기 수립',
    ],
    logIds: [
      'WD-020',
    ],
    occurrences: 4,
    metrology: 'Ellipsometry/OCD',
    lastSeen: '2026-03-10',
    openCase: false,
  },
  {
    id: 'deposition-edgeloc-2',
    process: 'DEPOSITION',
    pattern: 'Edge-Loc',
    variant: 2,
    name: 'Slit Valve 개폐 시 Particle 유입으로 인한 방향성 Particle 불량',
    mechanism: [
      '웨이퍼가 드나드는 Slit Valve는 챔버 내 특정 방향에 고정되어 있음',
      '밸브 개폐 시 발생하는 기류나 마찰로 인해 유입된 Particle이 항상 밸브와 가장 가까운 방향의 웨이퍼 Edge 영역에 국소적으로 부착',
    ],
    waferMap: 'Edge 영역 중 Slit Valve 위치와 가까운 특정 부위에 Particle 등의 Defect Count가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      '동일 방향 반복 검출 Lot Wet Clean 진행 후 재검사',
      'Slit Valve 인접 위치 웨이퍼 우선 전수검사',
    ],
    improvement: [
      'Slit Valve Purge 강화',
    ],
    logIds: [
      'WD-021',
    ],
    occurrences: 5,
    metrology: 'DF Inspection',
    lastSeen: '2026-04-19',
    openCase: false,
    directional: {
      kind: 'fixed',
      clock: 9,
      label: '9시 방향',
    },
  },
  {
    id: 'deposition-loc-2',
    process: 'DEPOSITION',
    pattern: 'Loc',
    variant: 2,
    name: 'Lift Pin 물리적 접촉 불량으로 인한 방향성 Particle 불량',
    mechanism: [
      '웨이퍼를 지지하는 3 Point Lift Pin이 챔버 내 고정된 각도에 위치함',
      '웨이퍼 뒷면/앞면 특정 지점에 핀 자국이 남음',
      '핀이 닿았던 특정 고정 위치를 중심으로 증착 이상이나 Particle 결함이 반복적으로 발생',
    ],
    waferMap: '국소 영역에 Particle 등의 Defect Count가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      'Lift Pin 정렬 상태 점검',
      '접촉부 이상 유무 확인 후 이상 시 부품 교체',
      '고정 위치 반복 검출 Lot Particle 재검사',
    ],
    improvement: [
      'Lift Pin 소재 및 형상 개선',
    ],
    logIds: [
      'WD-022',
    ],
    occurrences: 4,
    metrology: 'DF Inspection',
    lastSeen: '2026-03-20',
    openCase: false,
    directional: {
      kind: 'layout',
      label: '장비 구조 의존',
    },
  },
  {
    id: 'deposition-scratch-2',
    process: 'DEPOSITION',
    pattern: 'Scratch',
    variant: 2,
    name: 'Boat Transfer Robot ARM 진입 방향 접촉으로 인한 방향성 Scratch 불량',
    mechanism: [
      'Transfer Robot의 End Effector는 설정된 동선에 따라 항상 동일한 방향과 각도로 웨이퍼를 픽업 및 삽입 진행',
      'ARM의 진입 각도 및 Grip force 이상으로 웨이퍼를 픽업 및 삽입할 때 접촉 마찰이 동일한 위치에 발생하는 불량 발생',
    ],
    waferMap: '특정 위치에 고정적으로 나타나는 선형 Scratch가 Defect Count로 검출되어 불량으로 분류된 형태',
    resolution: [
      'Scratch 검출 위치의 Robot ARM 진입 각도 및 Grip force를 Dummy Wafer로 점검',
      '고정 방향 반복 검출 Lot 전수 재검사로 심각도 판정',
    ],
    improvement: [
      'Robot ARM 진입 각도·Grip Force 정기 점검 주기 수립',
    ],
    logIds: [
      'WD-023',
    ],
    occurrences: 5,
    metrology: 'DF Inspection',
    lastSeen: '2026-04-29',
    openCase: false,
    directional: {
      kind: 'fixed',
      clock: 3,
      label: '3시 방향',
    },
  },
  {
    id: 'deposition-nearfull-2',
    process: 'DEPOSITION',
    pattern: 'Near-full',
    variant: 2,
    name: 'RF Power/Gas Flow 전체 이상으로 인한 Deposition 미발생 불량',
    mechanism: [
      '증착 공정 시작 시 Plasma Ignition에 실패하거나 핵심 반응 가스 밸브가 열리지 않아 챔버 내로 가스가 아예 공급되지 않는 시스템 다운 발생',
      '반응물 미공급으로 인한 박막 증착 실패로 박막 두께(THK)가 Spec 대비 0에 가깝게 측정되는 미증착 불량 발생',
    ],
    waferMap: '전체 영역에 걸쳐 박막 두께(THK)가 Spec보다 작아 불량으로 분류된 형태',
    resolution: [
      'Deposition 미발생 확인 시 즉시 공정 중단',
      'Dummy Wafer로 재차 공정 진행해 이상 없는지 확인',
    ],
    improvement: [
      '장비 센서 데이터(FDC) 기반 실시간 이상 감지 시스템 강화',
    ],
    logIds: [
      'WD-024A',
      'WD-024B',
    ],
    occurrences: 4,
    metrology: 'Ellipsometry/OCD',
    lastSeen: '2026-01-21',
    openCase: false,
  },
  {
    id: 'photo-center-1',
    process: 'PHOTO',
    pattern: 'Center',
    variant: 1,
    name: 'Spin Coating Dispense Nozzle 정렬 오차로 인한 CD Over 불량',
    mechanism: [
      'PR 용액의 Discharge가 웨이퍼 중심에 위치한 Nozzle에서 시작됨',
      '이때 Nozzle의 위치가 중심부에서 벗어나면 중심부의 PR 두께가 두껍게 형성',
      'PR 두께가 두꺼우면 원하는 패턴 크기보다 크게 형성되면서 CD가 Spec보다 커지는 불량 발생',
    ],
    waferMap: '중심부의 CD가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      'Nozzle과 Chuck의 중심 간의 틀어짐 정렬',
      '중심부 CD 재계측으로 정상화 확인',
    ],
    improvement: [
      '주기적 Calibration 진행',
    ],
    logIds: [
      'WD-025',
    ],
    occurrences: 3,
    metrology: 'CD-SEM',
    lastSeen: '2026-02-28',
    openCase: false,
  },
  {
    id: 'photo-edgering-1',
    process: 'PHOTO',
    pattern: 'Edge-Ring',
    variant: 1,
    name: 'Edge Bead Removal (EBR) 설정 오류로 인한 Edge PR 잔류 불량',
    mechanism: [
      'Edge 영역 PR을 의도적으로 노광·제거하는 WEE 공정에서 노광 범위 및 Dose, Solvent의 분사량이 설정치에서 벗어남',
      'Edge 영역 전체에 균일하게 PR이 잔류하거나 과다 제거됨',
      'Under WEE로 노광 혹은 PR Solvent의 양이 부족할 시 Edge 영역 Ring을 따라 PR Residue·Bridge Defect가 증가하는 불량 발생',
      'Over WEE로 노광 혹은 PR Solvent의 양이 과다할 시 Active 영역까지 침범해 CD Loss 불량 발생',
    ],
    waferMap: 'Under WEE: Edge 영역 전체에 PR Residue 등의 Defect Count가 Spec보다 커서 불량으로 분류된 형태 Over WEE: Edge 영역 전체에 CD가 Spec보다 작아서 불량으로 분류된 형태',
    resolution: [
      'WEE 노광 범위 및 Dose Re-Calibration',
      'EBR Solvent Nozzle 위치·유량 점검',
      'Edge 영역 CD Spec 이탈 재계측으로 정상화 확인',
    ],
    improvement: [
      'EBR Solvent Nozzle 정기 점검 주기 수립',
    ],
    logIds: [
      'WD-026A',
      'WD-026B',
    ],
    occurrences: 6,
    metrology: 'Defect(WIS) Inspection',
    lastSeen: '2026-03-08',
    openCase: false,
  },
  {
    id: 'photo-edgeloc-1',
    process: 'PHOTO',
    pattern: 'Edge-Loc',
    variant: 1,
    name: 'Track Chuck Pin 접촉점 오염으로 인한 Particle 불량',
    mechanism: [
      'Coating/Develop 단계에서 Chuck Pin 접촉점에 Particle이 국소적으로 부착',
      '접촉 위치가 일정하지 않아 방향성 없이 Edge 영역의 국소 부위에 Particle 불량 발생',
    ],
    waferMap: 'Edge 영역 중 국소 부위에 Particle 등의 Defect Count가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      'Chuck Pin Cleaning',
      'Particle Count 초과 검출 Lot 재검사',
    ],
    improvement: [
      'Chuck Pin 정기 세정 주기 수립',
    ],
    logIds: [
      'WD-027',
    ],
    occurrences: 4,
    metrology: 'Defect(WIS) Inspection',
    lastSeen: '2026-04-15',
    openCase: false,
  },
  {
    id: 'photo-random-1',
    process: 'PHOTO',
    pattern: 'Random',
    variant: 1,
    name: 'Track/Scanner Ambient 오염으로 인한 Particle 불량',
    mechanism: [
      '웨이퍼 이송 경로 전반의 Ambient 오염 존재',
      '무작위 위치에 Particle·기포 결함이 발생',
      '무작위하게 Particle 불량이 발생',
    ],
    waferMap: '무작위한 영역에서 Particle 등의 Defect Count가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      '무작위 Particle Count 초과 Lot Wet Clean 진행 후 재검사',
    ],
    improvement: [
      'Track 이송경로 Particle 모니터링',
      'TM Purge 강화',
    ],
    logIds: [
      'WD-028A',
      'WD-028B',
    ],
    occurrences: 6,
    metrology: 'Defect(WIS) Inspection',
    lastSeen: '2026-03-18',
    openCase: false,
  },
  {
    id: 'photo-scratch-1',
    process: 'PHOTO',
    pattern: 'Scratch',
    variant: 1,
    name: 'Track Wafer Handler/Chuck Pin 접촉으로 인한 Scratch 불량',
    mechanism: [
      '여러 모듈 간 이송이 많아 Handler/Chuck Pin의 임의 위치에 대한 접촉이 다수 발생',
      '마찰이 임의 위치에서 발생하면서 방향성 없는 선형 Scratch 불량 발생',
    ],
    waferMap: '임의 방향의 선형 Scratch가 Defect Count로 검출되어 불량으로 분류된 형태',
    resolution: [
      'Handler 마모 확인 후 이상 시 교체',
      'Scratch Defect Count 전수 재검사로 심각도 판정',
    ],
    improvement: [
      'Handler 접촉면 소재 개선',
      '이송 속도 최적화',
    ],
    logIds: [
      'WD-029A',
      'WD-029B',
    ],
    occurrences: 8,
    metrology: 'Defect(WIS) Inspection',
    lastSeen: '2026-04-27',
    openCase: false,
  },
  {
    id: 'photo-nearfull-1',
    process: 'PHOTO',
    pattern: 'Near-full',
    variant: 1,
    name: 'Scanner Dose 오류로 인한 전면 CD 불량',
    mechanism: [
      'Dose가 Spec을 크게 벗어나면 웨이퍼 전체 PR Profile이 붕괴',
      'Under-exposure 시 PR 과다 잔류로 CD가 Spec보다 큰 CD Over 불량 발생',
      'Over-exposure 시 PR 과소·패턴 소실로 CD가 Spec보다 작거나 형성되지 않는 CD Loss 불량 발생',
    ],
    waferMap: '전체 영역의 CD가 Spec을 벗어나 불량으로 분류된 형태',
    resolution: [
      'Dose 이상 확인 시 즉시 노광 중단',
      '전면 CD 이상 Lot 전량 격리 후 전수검사',
    ],
    improvement: [
      'Dose 실시간 모니터링',
      'FEM 기반 Process Margin 재검증',
    ],
    logIds: [
      'WD-030A',
      'WD-030B',
    ],
    occurrences: 4,
    metrology: 'CD-SEM',
    lastSeen: '2026-02-21',
    openCase: false,
  },
  {
    id: 'photo-edgeloc-2',
    process: 'PHOTO',
    pattern: 'Edge-Loc',
    variant: 2,
    name: 'Wafer Edge Expose (WEE) 공정 중 헤드 시작/종료 지점 노광량 편차로 인한 방향성 CD 불량',
    mechanism: [
      'Edge 영역을 스캔하며 노광하는 WEE의 스캔 시작·종료 지점에서 노광량 편차가 발생',
      'Edge 영역 중 국소 부위에서만 CD가 Spec보다 작아지는 불량 발생',
    ],
    waferMap: 'Edge 영역 중 스캔 시작/종료 위치의 CD가 Spec보다 작아서 불량으로 분류된 형태',
    resolution: [
      '국소 CD Spec 이탈 위치 확인 시 해당 Lot 격리 후 CD 재계측',
    ],
    improvement: [
      '시작/종료 지점 노광량 균일화',
      'Overlap 구간 재설계',
    ],
    logIds: [
      'WD-031',
    ],
    occurrences: 4,
    metrology: 'CD-SEM',
    lastSeen: '2026-05-05',
    openCase: false,
    directional: {
      kind: 'layout',
      label: '장비 구조 의존',
    },
  },
  {
    id: 'photo-random-2',
    process: 'PHOTO',
    pattern: 'Random',
    variant: 2,
    name: 'PR Bubble로 인한 Particle 불량',
    mechanism: [
      'PR Dispense 시 혼입된 Bubble이 원인',
      '무작위하게 Particle 불량이 발생',
    ],
    waferMap: '무작위한 영역에서 Particle 등의 Defect Count가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      '무작위 Particle Count 초과 Lot Wet Clean 진행 후 재검사',
    ],
    improvement: [
      'PR Dispense line의 Bubble 억제 관리',
    ],
    logIds: [
      'WD-032',
    ],
    occurrences: 4,
    metrology: 'Defect(WIS) Inspection',
    lastSeen: '2026-05-10',
    openCase: false,
  },
  {
    id: 'photo-scratch-2',
    process: 'PHOTO',
    pattern: 'Scratch',
    variant: 2,
    name: 'Track Robot ARM 진입 방향 접촉으로 인한 방향성 Scratch 불량',
    mechanism: [
      'Track Robot ARM은 고정된 모듈 간 이송 경로를 따라 동일한 방향과 각도로 웨이퍼를 픽업 및 삽입 진행',
      'ARM의 진입 각도 및 Grip force 이상으로 웨이퍼를 픽업 및 삽입할 때 접촉 마찰이 동일한 위치에 발생하는 불량 발생',
    ],
    waferMap: '특정 위치에 고정적으로 나타나는 선형 Scratch가 Defect Count로 검출되어 불량으로 분류된 형태',
    resolution: [
      'Scratch 방향-Track 레이아웃 대조',
      'Scratch 검출 위치의 Robot ARM 진입 각도 및 Grip force를 Dummy Wafer로 점검',
    ],
    improvement: [
      'Robot ARM 진입 각도·Grip Force 정기 점검 주기 수립',
    ],
    logIds: [
      'WD-033',
    ],
    occurrences: 5,
    metrology: 'Defect(WIS) Inspection',
    lastSeen: '2026-06-19',
    openCase: false,
    directional: {
      kind: 'fixed',
      clock: 3,
      label: '3시 방향',
    },
  },
  {
    id: 'photo-nearfull-2',
    process: 'PHOTO',
    pattern: 'Near-full',
    variant: 2,
    name: 'Develop 전체 실패로 인한 전면 패턴 미형성 불량',
    mechanism: [
      '현상액 농도·시간이 Spec을 벗어나면 웨이퍼 전면의 패턴 형성이 실패',
      '전면 패턴 미형성 또는 잔여 PR이 전면에 검출',
    ],
    waferMap: '전체 영역에서 패턴 미형성 또는 잔여 PR이 검출되어 불량으로 분류된 형태',
    resolution: [
      '현상액 점검',
      '전면 패턴 미형성 Lot 전량 격리 후 전수검사',
    ],
    improvement: [
      '현상액 농도 실시간 관리 강화',
      'DEV Recipe 재검토',
    ],
    logIds: [
      'WD-034A',
      'WD-034B',
      'WD-034C',
      'WD-034D',
    ],
    occurrences: 8,
    metrology: 'Defect(WIS) Inspection',
    lastSeen: '2026-03-17',
    openCase: false,
  },
  {
    id: 'etch-center-1',
    process: 'ETCH',
    pattern: 'Center',
    variant: 1,
    name: 'RF Power 챔버 Matching 불일치로 인한 Over-Etch 불량',
    mechanism: [
      '식각 챔버의 RF Power와 주파수 간의 Matching 불일치가 발생해 웨이퍼 중앙부근에 Plasma Density가 높게 형성됨',
      '반응성 이온과 라디칼이 중심에 집중되어 중심부의 Etch Rate가 급격하게 상승해 중앙부의 박막이 빠르게 깎여나감',
      '웨이퍼 전체에 동일한 시간동안 식각 진행되면서 중심부 CD가 Spec보다 작아지는 Over-Etch 불량 발생',
    ],
    waferMap: '중심부의 CD가 Spec보다 작아서 불량으로 분류된 형태',
    resolution: [
      '중심부 CD Spec 이탈 확인 시 해당 Lot 격리 후 RF Matching 상태 실측 점검',
      'CD 재계측으로 Spec 이탈 범위 확정',
    ],
    improvement: [
      'RF Matcher 내부 커패시터 정비 및 튜닝',
      'RF 주파수 재검토',
    ],
    logIds: [
      'WD-035',
    ],
    occurrences: 4,
    metrology: 'CD-SEM',
    lastSeen: '2026-05-26',
    openCase: false,
  },
  {
    id: 'etch-donut-1',
    process: 'ETCH',
    pattern: 'Donut',
    variant: 1,
    name: 'ICP Coil 자기장 분포 편차로 인한 Etch Rate 불균일 불량',
    mechanism: [
      'ICP Type의 식각 챔버에서 상단 코일의 자기장이 완벽히 분산되지 못하고 특정 반경대에서만 최대가 되도록 편향됨',
      '자기장이 센 특정 반경대를 따라 Plasma Density가 띠 모양으로 밀집되면서 해당 영역의 Etch Rate가 급격하게 상승해 띠 영역의 박막이 빠르게 깎여나감',
      '웨이퍼 전체에 동일한 시간동안 식각 진행되면서 Ring 형태로 CD가 Spec보다 작아지는 Over-Etch 불량 발생',
    ],
    waferMap: '띠 영역의 CD가 Spec보다 작아서 불량으로 분류된 형태',
    resolution: [
      '띠 영역 CD Spec 이탈 확인 시 해당 Lot 격리 후 Inner/Outer Coil Power 실측값 기록 확인',
    ],
    improvement: [
      '챔버 벽면 Coil의 물리적 배치 재설계',
      'Inner/Outer Coil의 Power 재설정',
    ],
    logIds: [
      'WD-036',
    ],
    occurrences: 4,
    metrology: 'CD-SEM',
    lastSeen: '2026-05-31',
    openCase: false,
  },
  {
    id: 'etch-edgering-1',
    process: 'ETCH',
    pattern: 'Edge-Ring',
    variant: 1,
    name: 'Focus Ring 마모로 인한 Edge 영역의 Etch Rate 편차 불량',
    mechanism: [
      'Edge 영역을 감싸는 Focus Ring이 마모되면 그 지점의 Sheath 형상이 왜곡됨',
      '이온 수직입사가 흐트러져 Edge 영역의 Etch Rate와 Etch Profile이 달라지면서 해당 영역의 Etch Rate가 급격하게 하락',
      '웨이퍼 전체에 동일한 시간동안 식각 진행되면서 Edge 영역의 CD가 Spec보다 커지는 Under-Etch 불량 발생',
    ],
    waferMap: 'Edge 영역 전체의 CD가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      'Focus Ring 이상 여부 확인 및 교체',
      'Edge 영역 CD 재계측으로 정상화 확인',
    ],
    improvement: [
      'Focus Ring 마모도에 따른 교체 주기 관리 강화',
      'Edge Compensation Recipe 적용',
    ],
    logIds: [
      'WD-037',
    ],
    occurrences: 4,
    metrology: 'CD-SEM',
    lastSeen: '2026-06-05',
    openCase: false,
  },
  {
    id: 'etch-edgeloc-1',
    process: 'ETCH',
    pattern: 'Edge-Loc',
    variant: 1,
    name: '챔버 내벽 누적막 탈피로 인한 Particle 불량',
    mechanism: [
      '챔버 내벽에 누적되어 있던 폴리머나 증착 부산물이 한계치에 도달해 탈락하면서 Particle이 떨어짐',
      '챔버가 웨이퍼를 감싸고 있는 형태라 내벽에 가까운 웨이퍼 Edge 영역 중 국소 부위에 집중적으로 Particle 발생',
    ],
    waferMap: 'Edge 영역 중 국소 부위에 Particle 등의 Defect Count가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      '챔버 Cleaning 진행',
      'Particle Count 초과 검출 Lot 재검사',
    ],
    improvement: [
      'RPS를 활용한 In-situ Clean 주기 관리 강화',
    ],
    logIds: [
      'WD-038',
    ],
    occurrences: 4,
    metrology: 'DF Inspection',
    lastSeen: '2026-06-10',
    openCase: false,
  },
  {
    id: 'etch-loc-1',
    process: 'ETCH',
    pattern: 'Loc',
    variant: 1,
    name: 'Gas Injector/Showerhead 국소 이상으로 인한 CD 불균일 불량',
    mechanism: [
      'Gas Injector/Showerhead의 분사구나 특정 미세 구멍들이 부산물로 막히는 등의 이상 발생',
      '해당 위치의 유량이 달라져 국소 영역에 Etch Rate 편차가 발생',
      '웨이퍼 전체에 동일한 시간동안 식각 진행되면서 국소 영역의 CD가 Spec보다 커지는 Under-Etch 불량 발생',
    ],
    waferMap: '국소 영역의 CD가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      'Injector/Showerhead 구멍별 유량 점검',
      '막힘·이상 부위 확인 시 부품 교체',
      '국소 CD 재계측으로 Spec 이탈 범위 확정',
    ],
    improvement: [
      'Injector/Showerhead 정기 세정·교체 주기 수립',
    ],
    logIds: [
      'WD-039A',
      'WD-039B',
    ],
    occurrences: 6,
    metrology: 'CD-SEM',
    lastSeen: '2026-05-13',
    openCase: false,
  },
  {
    id: 'etch-random-1',
    process: 'ETCH',
    pattern: 'Random',
    variant: 1,
    name: '챔버 내부 식각 부산물의 Redeposition으로 인한 Particle 불량',
    mechanism: [
      'Exhaust 유량 문제 발생 등이 원인이 되어 챔버 내부에 식각 부산물이 잔류',
      '잔류한 부산물이 웨이퍼 전반에 무작위하게 재부착되고, 일부는 증착 반응까지 발생',
      '무작위하게 Particle 불량이 발생',
    ],
    waferMap: '무작위한 영역에서 Particle 등의 Defect Count가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      '챔버 Wet/Dry Cleaning 진행',
      '무작위 Particle Count 초과 Lot 재검사',
    ],
    improvement: [
      'Wet/Dry Cleaning 주기 관리 강화',
      'Exhaust 유량 최적화',
    ],
    logIds: [
      'WD-040',
    ],
    occurrences: 4,
    metrology: 'DF Inspection',
    lastSeen: '2026-06-20',
    openCase: false,
  },
  {
    id: 'etch-scratch-1',
    process: 'ETCH',
    pattern: 'Scratch',
    variant: 1,
    name: 'ESC Lift Pin 접촉으로 인한 Scratch 불량',
    mechanism: [
      'Loading/Un-Loading 시 웨이퍼를 지지하는 3 Point Lift Pin이 접촉하며 물리적 손상 발생',
      'Lift Pin이 닿는 특정 고정 위치를 중심으로 마찰이 발생하면서 선형 Scratch 불량 발생',
    ],
    waferMap: 'Lift Pin 위치에 선형 Scratch가 Defect Count로 검출되어 불량으로 분류된 형태',
    resolution: [
      'Lift Pin 정렬 상태 점검',
      '접촉부 이상 유무 확인 후 이상 시 교체',
      'Scratch Defect Count 전수 재검사로 심각도 판정',
    ],
    improvement: [
      'Lift Pin 소재 및 형상 개선',
    ],
    logIds: [
      'WD-041',
    ],
    occurrences: 5,
    metrology: 'DF Inspection',
    lastSeen: '2026-07-30',
    openCase: false,
  },
  {
    id: 'etch-nearfull-1',
    process: 'ETCH',
    pattern: 'Near-full',
    variant: 1,
    name: '플라즈마 발생 이상으로 인한 전면 미식각 불량',
    mechanism: [
      'Plasma Ignition 실패, RF Power, Gas 주입 등의 문제로 Plasma가 형성되지 않거나 Gas가 공급되지 않으면 식각이 전혀 진행되지 않음',
      '식각 전 두께가 그대로 유지되어 박막의 두께가 변하지 않는 불량 발생',
    ],
    waferMap: '전체 영역의 박막 두께(THK)가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      'Igniter 이상 확인 및 교체',
      'Dummy Wafer로 재차 공정 진행해 이상 없는지 확인',
      '미식각 Lot 전량 격리 후 전수검사',
    ],
    improvement: [
      'Igniter 이상 확인 및 교체',
      'Dummy Wafer로 재차 공정 진행해 이상 없는지 확인',
      '장비 센서 데이터(FDC) 기반 실시간 이상 감지 시스템 강화',
    ],
    logIds: [
      'WD-042A',
      'WD-042B',
      'WD-042C',
    ],
    occurrences: 6,
    metrology: 'EM Box',
    lastSeen: '2026-04-25',
    openCase: false,
  },
  {
    id: 'etch-edgeloc-2',
    process: 'ETCH',
    pattern: 'Edge-Loc',
    variant: 2,
    name: 'Slit Valve 개폐 시 Particle 유입으로 인한 방향성 Particle 불량',
    mechanism: [
      '웨이퍼가 드나드는 Slit Valve는 챔버 내 특정 방향에 고정되어 있음',
      '밸브 개폐 시 발생하는 기류나 마찰로 인해 유입된 Particle이 항상 밸브와 가장 가까운 방향의 웨이퍼 Edge 영역에 국소적으로 부착',
    ],
    waferMap: 'Edge 영역 중 Slit Valve 위치와 가까운 특정 부위에 Particle 등의 Defect Count가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      '동일 방향 반복 검출 Lot Wet Clean 진행 후 재검사',
      'Slit Valve 인접 위치 웨이퍼 우선 전수검사',
    ],
    improvement: [
      'Slit Valve Purge 강화',
    ],
    logIds: [
      'WD-043',
    ],
    occurrences: 5,
    metrology: 'DF Inspection',
    lastSeen: '2026-08-05',
    openCase: false,
    directional: {
      kind: 'fixed',
      clock: 9,
      label: '9시 방향',
    },
  },
  {
    id: 'etch-loc-2',
    process: 'ETCH',
    pattern: 'Loc',
    variant: 2,
    name: 'RF Feedthrough 근처 국소 E-field 이상으로 인한 방향성 CD 불량',
    mechanism: [
      'RF 전력이 유입되는 Feedthrough는 챔버 내 고정 위치라 그 근처에 국소 E-field 이상이 발생',
      '인접한 고정 방향에서 CD가 국소적으로 이탈하며 매 웨이퍼 동일 위치에 반복되는 불량 발생',
    ],
    waferMap: 'RF Feedthrough 인접 고정 방향의 국소 CD가 Spec을 벗어나 불량으로 분류된 형태',
    resolution: [
      '국소 CD Spec 이탈 위치 확인 시 해당 Lot 격리 후 CD 재계측',
    ],
    improvement: [
      'Feedthrough 주변 Plasma Density 시뮬레이션 검증',
    ],
    logIds: [
      'WD-044',
    ],
    occurrences: 4,
    metrology: 'CD-SEM',
    lastSeen: '2026-07-10',
    openCase: false,
    directional: {
      kind: 'layout',
      label: '장비 구조 의존',
    },
  },
  {
    id: 'etch-scratch-2',
    process: 'ETCH',
    pattern: 'Scratch',
    variant: 2,
    name: 'Wafer Handler Robot ARM 진입 방향 접촉으로 인한 방향성 Scratch 불량',
    mechanism: [
      '방사형으로 배치된 Chamber에 Handler Robot ARM이 고정된 각도로 진입하며 항상 동일한 방향과 각도로 웨이퍼를 픽업 및 삽입 진행',
      'ARM의 진입 각도 및 Grip force 이상으로 웨이퍼를 픽업 및 삽입할 때 접촉 마찰이 동일한 위치에 발생하는 불량 발생',
    ],
    waferMap: '특정 위치에 고정적으로 나타나는 선형 Scratch가 Defect Count로 검출되어 불량으로 분류된 형태',
    resolution: [
      'Scratch 검출 위치의 Robot ARM 진입 각도 및 Grip force를 Dummy Wafer로 점검',
      '고정 방향 반복 검출 Lot 전수 재검사로 심각도 판정',
    ],
    improvement: [
      'Robot ARM 진입 각도·Grip Force 정기 점검 주기 수립',
    ],
    logIds: [
      'WD-045',
    ],
    occurrences: 5,
    metrology: 'DF Inspection',
    lastSeen: '2026-08-04',
    openCase: false,
    directional: {
      kind: 'fixed',
      clock: 3,
      label: '3시 방향',
    },
  },
  {
    id: 'etch-nearfull-2',
    process: 'ETCH',
    pattern: 'Near-full',
    variant: 2,
    name: 'EOP(Endpoint) 오검출로 인한 전면 Over/Under Etch 불량',
    mechanism: [
      'Optical Emission 신호를 오판독하면 웨이퍼 전면이 동일하게 영향을 받음',
      '웨이퍼 전체가 식각이 진행되지 않은 것 처럼 두께가 측정되는 불량 발생',
    ],
    waferMap: '전체 영역에서 박막 두께(THK)가 Spec을 벗어나 불량으로 분류된 형태',
    resolution: [
      'EOP 오검출 확인 시 즉시 공정 중단',
      '전면 CD/두께 이상 Lot 전량 격리 후 전수검사',
    ],
    improvement: [
      '다파장 EOP 알고리즘 도입',
      'EOP 신호 이중검증',
    ],
    logIds: [
      'WD-046A',
      'WD-046B',
    ],
    occurrences: 4,
    metrology: 'EM Box',
    lastSeen: '2026-05-14',
    openCase: false,
  },
  {
    id: 'cleaning-donut-1',
    process: 'CLEANING',
    pattern: 'Donut',
    variant: 1,
    name: 'Wet Single Clean 중 Nozzle 체류시간 편차로 인한 불순물 잔류 불량',
    mechanism: [
      '웨이퍼를 회전시키며 세정액을 분사하는 Nozzle이 Center에서 Edge로 Sweep할 때 특정 반경대에서 세정액 분사량이 부족',
      '화학물질의 유속 느려짐, Nozzle 체류시간 단축이 원인',
      '세정액 분사량이 부족한 특정 반경대에서 웨이퍼 표면의 오염물질이나 찌꺼기가 완전히 씻겨나가지 못하고 잔류함',
    ],
    waferMap: '세정이 덜 된 특정 반경대를 따라 Particle 등의 Defect Count가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      '특정 반경대 Particle 잔류 확인 시 해당 Lot Nozzle Flow Rate 실측 점검 후 Wet Clean 재진행',
    ],
    improvement: [
      'Nozzle의 Sweep 속도 프로파일 변경',
      '화학물질 Spray Pattern 재설계',
    ],
    logIds: [
      'WD-047',
    ],
    occurrences: 3,
    metrology: 'Macro/DF Inspection',
    lastSeen: '2026-06-21',
    openCase: false,
  },
  {
    id: 'cleaning-edgering-1',
    process: 'CLEANING',
    pattern: 'Edge-Ring',
    variant: 1,
    name: 'Wet Single Spin 세정 시 Edge 영역 원심력에 의한 케미컬 체류시간 부족으로 인한 Edge Ring 세정 불량',
    mechanism: [
      '웨이퍼를 고속 회전시키며 세정액을 분사하는 과정에서 회전 반경이 가장 큰 Edge 영역에서 선속도가 최대',
      'Edge 영역에 강한 원심력이 가해져 세정액이 빠르게 튕겨 나가 케미컬 체류시간이 부족해짐',
      'Edge 영역 전체를 따라 세정력이 저하되어 오염물·잔류물이 남는 불량 발생',
    ],
    waferMap: 'Edge 영역 전체에 Particle 등의 Defect Count가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      '회전속도 프로파일 재설정',
      'Edge 영역 세정액 분사량·체류시간 보정',
      'Edge 영역 Particle Count 재검사로 정상화 확인',
    ],
    improvement: [
      'Nozzle Sweep 속도 프로파일 조정',
    ],
    logIds: [
      'WD-048',
    ],
    occurrences: 4,
    metrology: 'Macro/DF Inspection',
    lastSeen: '2026-07-31',
    openCase: false,
  },
  {
    id: 'cleaning-edgeloc-1',
    process: 'CLEANING',
    pattern: 'Edge-Loc',
    variant: 1,
    name: 'Wet Single Chuck Pin 접촉점 오염으로 인한 Particle 불량',
    mechanism: [
      '고정 Chuck Pin 접촉점에 오염물이 국소적으로 잔류',
      '접촉 위치가 일정하지 않아 방향성 없이 Edge 영역 국소 부위에 Particle 불량 발생',
    ],
    waferMap: 'Edge 영역 중 국소 부위에 Particle 등의 Defect Count가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      'Chuck Pin 접촉 위치 확인 시 즉시 Cleaning 실시',
      'Particle Count 초과 검출 Lot 재검사',
    ],
    improvement: [
      'Chuck Pin 정기 세정',
    ],
    logIds: [
      'WD-049',
    ],
    occurrences: 4,
    metrology: 'Macro/DF Inspection',
    lastSeen: '2026-08-05',
    openCase: false,
  },
  {
    id: 'cleaning-loc-1',
    process: 'CLEANING',
    pattern: 'Loc',
    variant: 1,
    name: 'Cross Contamination 기인 불순물 재흡착에 의한 Particle 불량',
    mechanism: [
      'Bath를 공유하면서 발생한 Cross Contamination에 의해 불순물이 재흡착되어 결함을 유발',
      '임의 위치에 집중되어 Particle 불량 발생',
    ],
    waferMap: '국소 영역에 Particle 등의 Defect Count가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      '케미컬 Bath내 세정액 교체',
      '동일 Bath 공유 인접 Lot 전수 재검사',
    ],
    improvement: [
      '세정액 교체 주기 단축',
      'Single Type 전환 검토',
    ],
    logIds: [
      'WD-050',
    ],
    occurrences: 4,
    metrology: 'Macro/DF Inspection',
    lastSeen: '2026-08-04',
    openCase: false,
  },
  {
    id: 'cleaning-random-1',
    process: 'CLEANING',
    pattern: 'Random',
    variant: 1,
    name: 'Fume으로 인한 Particle 불량',
    mechanism: [
      '사용한 케미컬이 웨이퍼·FOUP에 미세입자로 잔류해 박막과 재반응하며 무작위 위치에 결함을 유발',
      '위치 재현성 없이 웨이퍼 전면에 무작위하게 Particle 불량이 발생',
    ],
    waferMap: '무작위한 영역에서 Particle 등의 Defect Count가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      '무작위 Particle Count 초과 Lot Wet Clean 진행 후 재검사',
      'FOUP 내부 Fume 잔류 여부 점검',
    ],
    improvement: [
      '세정 공정 강화',
      '공정 이후 세정 진행까지의 대기 시간 단축',
      'Exhaust 배기 강화로 Fume 재흡착 방지',
    ],
    logIds: [
      'WD-051',
    ],
    occurrences: 5,
    metrology: 'Macro/DF Inspection',
    lastSeen: '2026-08-02',
    openCase: false,
  },
  {
    id: 'cleaning-scratch-1',
    process: 'CLEANING',
    pattern: 'Scratch',
    variant: 1,
    name: 'Scrubber Brush 물리적 접촉으로 인한 Scratch 불량',
    mechanism: [
      'Brush가 Particle을 제거하는 과정에서 공정 이상 발생',
      '브러시 접촉면 전체에 걸쳐 선형 Scratch 불량 발생',
    ],
    waferMap: '브러시 접촉면 전반의 선형 Scratch가 Defect Count로 검출되어 불량으로 분류된 형태',
    resolution: [
      'PVA Brush 마모 확인 후 이상 시 교체',
      'Scratch Defect Count 전수 재검사로 심각도 판정',
    ],
    improvement: [
      'Brush 압력·회전속도 최적화',
    ],
    logIds: [
      'WD-052',
    ],
    occurrences: 5,
    metrology: 'Macro/DF Inspection',
    lastSeen: '2026-08-03',
    openCase: false,
  },
  {
    id: 'cleaning-nearfull-1',
    process: 'CLEANING',
    pattern: 'Near-full',
    variant: 1,
    name: '케미컬 농도/온도 전체 이상으로 인한 전면 세정 불량',
    mechanism: [
      '케미컬 농도 혹은 온도가 Spec을 벗어나면 케미컬의 세정력이 급격하게 변화',
      '세정 자체가 웨이퍼 전면에서 실패',
      '세정 부족 시 잔류 Particle 및 금속 부산물의 양 급증, 과세정 시 표면 손상성 결함이 증가하는 불량 발생',
    ],
    waferMap: '전체 영역에서 Particle 등의 Defect Count가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      '케미컬 저장소 및 이송 Nozzle 이상 유무 확인',
      '금속 부산물 검출 시 해당 Lot 전량 격리 후 Metallic Impurity 정밀분석 실시',
    ],
    improvement: [
      '실시간 농도계·온도 모니터링 시스템 점검',
    ],
    logIds: [
      'WD-053A',
      'WD-053B',
      'WD-053C',
      'WD-053D',
    ],
    occurrences: 8,
    metrology: 'Macro/DF Inspection',
    lastSeen: '2026-06-22',
    openCase: false,
  },
  {
    id: 'cleaning-edgering-2',
    process: 'CLEANING',
    pattern: 'Edge-Ring',
    variant: 2,
    name: 'Marangoni Effect 활용 건조 시 Edge 영역 표면장력 불균일로 인한 Watermark 불량',
    mechanism: [
      'Edge 영역은 기하학적으로 표면장력 구배가 다르게 형성됨',
      '건조 시 웨이퍼 회전에 의해 액체가 Edge 영역 전체를 따라 형태로 잔류하는 불량 발생',
    ],
    waferMap: 'Edge 영역 전체에 Watermark 등의 Defect Count가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      'IPA 농도 재설정',
      '건조 시간 및 회전속도 재설정',
      'Watermark 검출 Lot 재건조 후 재검사',
    ],
    improvement: [
      '초임계 건조 방식 도입 검토',
    ],
    logIds: [
      'WD-054',
    ],
    occurrences: 4,
    metrology: 'SEM(Pattern Collapse Rate)',
    lastSeen: '2026-08-03',
    openCase: false,
  },
  {
    id: 'cleaning-edgeloc-2',
    process: 'CLEANING',
    pattern: 'Edge-Loc',
    variant: 2,
    name: 'Batch Type 배스 하부 Nozzle 분사 편차로 인한 Edge 국소 부위 세정 불량',
    mechanism: [
      '케미컬을 Bath 하부 Nozzle에서 분사해 위로 밀어내는 방식으로 순환시키는 과정에서 문제 발생',
      '하부 Nozzle이 특정 위치에 고정 배치되어 있어 Nozzle과 어긋난 Edge 영역 중 국소 부위에서 순환 유량이 부족해짐',
      'Edge 영역 중 국소 부위에 세정력이 저하되어 오염물·잔류물이 남는 불량 발생',
    ],
    waferMap: 'Edge 영역 중 순환 유량이 부족한 국소 부위에 Particle 등의 Defect Count가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      'Edge 국소 부위 Particle 잔류 확인 시 해당 Lot Wet Clean 진행 후 재검사',
    ],
    improvement: [
      'Bath 하부 Nozzle 배치·분사 패턴 재설계',
      '케미컬 배스 순환 유량 상향',
      'Single Type 장비로의 전환 검토',
    ],
    logIds: [
      'WD-055',
    ],
    occurrences: 4,
    metrology: 'Macro/DF Inspection',
    lastSeen: '2026-08-03',
    openCase: false,
  },
  {
    id: 'cleaning-nearfull-2',
    process: 'CLEANING',
    pattern: 'Near-full',
    variant: 2,
    name: 'Marangoni 건조 실패로 인한 전면 Watermark 불량',
    mechanism: [
      '건조 공정이 실패하면 웨이퍼 전면에 물방울·잔류물이 발생',
      'Pattern Collapse와 Watermark 발생이 급증하는 불량 발생',
    ],
    waferMap: '전체 영역에서 Watermark 등의 Defect Count가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      'IPA 농도 재설정',
      '건조 시간 및 회전속도 재설정',
      '전면 Watermark 검출 Lot 전량 격리 후 SEM으로 Pattern Collapse 발생 여부 확인',
    ],
    improvement: [
      '초임계 건조 방식 도입 검토',
    ],
    logIds: [
      'WD-056',
    ],
    occurrences: 3,
    metrology: 'SEM(Pattern Collapse Rate)',
    lastSeen: '2026-08-04',
    openCase: false,
  },
  {
    id: 'cmp-center-1',
    process: 'CMP',
    pattern: 'Center',
    variant: 1,
    name: 'CMP Head 내 중심 Zone의 압력 이상으로 인한 Under-Polishing 불량',
    mechanism: [
      '원인1: 회전축의 중심에 스트레스가 집중되어 중심 Zone Membrane에 미세한 Pinhole, Crack 발생해 빈공간을 통해 공기가 유출되면서 압력 약화',
      '원인2: Zone 별 압력을 구분을 위한 O-ring의 마모로 인해 중심 Zone의 공기가 유출되면서 압력 약화',
      '결과: 압력이 약화되어 패드가 웨이퍼를 누르는 힘이 약화되어 중심부 Remaining Thickness(THK)가 Spec보다 커지는 Under-Polishing 불량 발생',
    ],
    waferMap: '중심부의 Remaining Thickness(THK)가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      '중심 Zone에만 공압 주입한 후 압력 유지되는지 확인한 뒤 Membrane',
      'O-Ring 교체',
      '중심부 Remaining Thickness(THK) 재계측으로 정상화 확인',
    ],
    improvement: [
      'Membrane 비정상 팽창·파손 여부 정기 점검 주기 수립',
    ],
    logIds: [
      'WD-057A',
      'WD-057B',
      'WD-057C',
    ],
    occurrences: 6,
    metrology: 'Post-CMP 광학 두께측정',
    lastSeen: '2026-07-09',
    openCase: false,
  },
  {
    id: 'cmp-donut-1',
    process: 'CMP',
    pattern: 'Donut',
    variant: 1,
    name: 'Retainer Ring 안쪽 압력 전이구간으로 인한 Polishing 양의 편차 불량',
    mechanism: [
      'Ring이 Edge 영역을 눌러주는 구조로 인해 그 안쪽 반경에 압력 전이구간이 형성',
      '전이구간에 해당하는 특정 반경대에서 접촉압이 국소적으로 커져 과하게 Polishing 발생',
    ],
    waferMap: 'Ring 안쪽 특정 반경대의 Remaining Thickness(THK)가 Spec보다 작아서 불량으로 분류된 형태',
    resolution: [
      '압력 프로파일 실측 점검',
      '반경대별 Remaining Thickness(THK) 재계측으로 Spec 이탈 범위 확정',
    ],
    improvement: [
      'Retainer Ring 높이·외경 스펙 재검토',
    ],
    logIds: [
      'WD-058',
    ],
    occurrences: 4,
    metrology: 'Post-CMP 광학 두께측정',
    lastSeen: '2026-08-03',
    openCase: false,
  },
  {
    id: 'cmp-edgering-1',
    process: 'CMP',
    pattern: 'Edge-Ring',
    variant: 1,
    name: 'Retainer Ring 마모로 인한 Edge Under-Polishing 불량',
    mechanism: [
      'Edge 영역을 눌러주는 Retainer Ring이 마모되면 Slip이나 Edge 영역 Under-Polishing이 발생',
      'Edge 영역 전체에 Polishing 부족으로 인해 Remaining Thickness(THK)가 Spec보다 두껍게 남는 불량 발생',
    ],
    waferMap: 'Edge 영역 전체의 Remaining Thickness(THK)가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      'Retainer Ring 마모 점검 후 이상 시 높이·외경 스펙 기준 교체',
      'Edge 영역 Remaining Thickness(THK) 재계측으로 정상화 확인',
    ],
    improvement: [
      'Retainer Ring 정기 측정 및 교체 주기 관리 강화',
    ],
    logIds: [
      'WD-059',
    ],
    occurrences: 4,
    metrology: 'Post-CMP 광학 두께측정',
    lastSeen: '2026-08-05',
    openCase: false,
  },
  {
    id: 'cmp-edgeloc-1',
    process: 'CMP',
    pattern: 'Edge-Loc',
    variant: 1,
    name: 'Retainer Ring Joint로 인한 방향성 Particle 불량',
    mechanism: [
      'Retainer Ring Joint 부근에서 Slurry 유입·배출이 불균일하게 반복됨',
      'Joint 접촉, Slurry 잔류로 인한 결함이 Joint 부근 특정 부위에 반복적으로 발생',
    ],
    waferMap: 'Edge 영역 중 Joint 인접 부위에 Particle 등의 Defect Count가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      'Joint 마모 및 오염 확인',
      'Particle Count 초과 검출 Lot 재검사',
    ],
    improvement: [
      'Joint 부근 Particle·Polishing 양상 집중 모니터링',
    ],
    logIds: [
      'WD-060',
    ],
    occurrences: 4,
    metrology: 'Inspection(DF)',
    lastSeen: '2026-08-04',
    openCase: false,
    directional: {
      kind: 'layout',
      label: '장비 구조 의존',
    },
  },
  {
    id: 'cmp-loc-1',
    process: 'CMP',
    pattern: 'Loc',
    variant: 1,
    name: 'Pad Pore 막힘으로 인한 국소 부위 Scratch 불량',
    mechanism: [
      'Pad 특정 부위의 Pore가 부산물로 막혀 배출 불량이 발생하면 해당 위치에 국소 Scratch를 유발',
      'Pad 위치에 대응해 무작위 국소 영역에 Scratch 불량 발생',
    ],
    waferMap: '국소 영역에 Scratch 등의 Defect Count가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      'Pad Pore 점검 및 Cleaning',
      'Scratch Defect Count 재검사로 심각도 판정',
    ],
    improvement: [
      'Pad Conditioning 강화',
      'Pore 구조 개선 Pad 채택',
    ],
    logIds: [
      'WD-061',
    ],
    occurrences: 4,
    metrology: 'Inspection(DF)',
    lastSeen: '2026-08-03',
    openCase: false,
  },
  {
    id: 'cmp-random-1',
    process: 'CMP',
    pattern: 'Random',
    variant: 1,
    name: 'Slurry 입자 Agglomeration으로 인한 Scratch 불량',
    mechanism: [
      'Slurry 입자가 응집되면 웨이퍼 표면 무작위 위치에서 Scratch를 유발',
      '위치 재현성 없이 무작위하게 Scratch성 결함이 발생하는 불량 발생',
    ],
    waferMap: '무작위한 영역에서 Scratch 등의 Defect Count가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      'Slurry Filter 여과율 실측 확인',
      '무작위 Scratch Defect Count 초과 Lot 재검사',
    ],
    improvement: [
      'Slurry Filter 여과율 관리',
      'Agglomeration 모니터링',
    ],
    logIds: [
      'WD-062',
    ],
    occurrences: 4,
    metrology: 'Inspection(DF)',
    lastSeen: '2026-08-05',
    openCase: false,
  },
  {
    id: 'cmp-scratch-1',
    process: 'CMP',
    pattern: 'Scratch',
    variant: 1,
    name: 'Slurry 내 강체 입자·Pad Pore 부산물로 인한 Scratch 불량',
    mechanism: [
      'Slurry 내 강체 입자나 Pad Pore 부산물로 인해 방향성 없는 선형 Scratch 불량 발생',
    ],
    waferMap: '임의 방향의 선형 Scratch가 Defect Count로 검출되어 불량으로 분류된 형태',
    resolution: [
      'Scratch Defect Count 초과 확인 시 해당 Lot 전수 재검사로 심각도 판정',
      'Pad Conditioning 상태 즉시 점검',
    ],
    improvement: [
      'Pad Pore 구조 개선',
      'CVD Conditioner 개선',
    ],
    logIds: [
      'WD-063A',
      'WD-063B',
    ],
    occurrences: 8,
    metrology: 'Inspection(DF)',
    lastSeen: '2026-08-04',
    openCase: false,
  },
  {
    id: 'cmp-nearfull-1',
    process: 'CMP',
    pattern: 'Near-full',
    variant: 1,
    name: 'EPD(End Point Detection) 오검출로 인한 전면 Polishing 불량',
    mechanism: [
      '공정 종료 시점 판단에 오류가 발생할 경우 웨이퍼 전면이 과도하거나 부족하게 Polishing',
      'Under-Polishing 시 Remaining Thickness(THK)가 Spec보다 크게, Over-Polishing 시 Remaining Thickness(THK)가 Spec보다 작은 불량 발생',
    ],
    waferMap: '전체 영역의 Remaining Thickness(THK)가 Spec을 벗어나 불량으로 분류된 형태',
    resolution: [
      'EPD 오검출 확인 시 즉시 공정 중단',
      '전면 Remaining Thickness(THK) 이상 Lot 전량 격리 후 전수검사',
    ],
    improvement: [
      '다파장 EPD 프로그램 도입',
      'EPD 신호 이중검증',
    ],
    logIds: [
      'WD-064A',
      'WD-064B',
    ],
    occurrences: 4,
    metrology: 'Post-CMP 광학 두께측정',
    lastSeen: '2026-08-05',
    openCase: false,
  },
  {
    id: 'cmp-center-2',
    process: 'CMP',
    pattern: 'Center',
    variant: 2,
    name: 'CMP Slurry Nozzle 위치 편중으로 인한 Over-Polishing 불량',
    mechanism: [
      '공정 중 Slurry Nozzle이 Pad의 중심부에 너무 가깝게 치우쳐서 정렬됨',
      '중심부에 슬러리가 집중되면서 해당 영역의 슬러리 농도가 Edge 영역보다 높게 유지되어 화학 반응이 과도하게 촉진',
      '중심부의 Polishing율이 급증해 Remaining Thickness(THK)가 Spec보다 얇아지는 Over-polishing 불량 발생',
    ],
    waferMap: '중심부의 Remaining Thickness(THK)가 Spec보다 작아서 불량으로 분류된 형태',
    resolution: [
      'Nozzle의 물리적 위치 재정렬',
      '중심부 Remaining Thickness(THK) 재계측으로 정상화 확인',
    ],
    improvement: [
      'Slurry가 Pad 전체에 균일하게 퍼지도록 Spray Pattern 재설계',
    ],
    logIds: [
      'WD-065',
    ],
    occurrences: 4,
    metrology: 'Post-CMP 광학 두께측정',
    lastSeen: '2026-08-03',
    openCase: false,
  },
  {
    id: 'cmp-donut-2',
    process: 'CMP',
    pattern: 'Donut',
    variant: 2,
    name: 'Pad Conditioning Sweep 경로에 따른 마모로 인한 Polishing 양의 편차 불량',
    mechanism: [
      'Conditioner Disk 왕복 경로가 특정 반경대에 집중되면 그 반경대의 Pad 거칠기에 편차가 발생',
      '컨디셔닝이 부족한 반경대는 Pad 거칠기 저하로 Polishing량이 감소해 Remaining Thickness(THK)가 Spec보다 크게 측정되는 불량 발생',
    ],
    waferMap: '특정 반경대의 Remaining Thickness(THK)가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      'PCR(Pad Cutting Rate) 실측 점검',
      '반경대별 Remaining Thickness(THK) 재계측으로 Spec 이탈 범위 확정',
    ],
    improvement: [
      'Sweep 경로 최적화',
    ],
    logIds: [
      'WD-066',
    ],
    occurrences: 4,
    metrology: 'Post-CMP 광학 두께측정',
    lastSeen: '2026-08-05',
    openCase: false,
  },
  {
    id: 'cmp-loc-2',
    process: 'CMP',
    pattern: 'Loc',
    variant: 2,
    name: 'Conditioner Disk Sweep Turn-around Point 편차로 인한 방향성 Over-Polishing 불량',
    mechanism: [
      '왕복 방향 전환의 양 끝단에서 Conditioner가 상대적으로 오래 머물거나 느려져 해당 위치 컨디셔닝이 과하게 진행',
      '해당 위치에 대응하는 반경 및 각도에서 Remaining Thickness(THK)가 Spec보다 낮아지는 Over-Polishing 불량 발생',
    ],
    waferMap: 'Turn-around Point 대응 위치의 Remaining Thickness(THK)가 Spec보다 작아서 불량으로 분류된 형태',
    resolution: [
      'Turn-around Point 대응 위치 Remaining Thickness(THK) Spec 이탈 확인 시 해당 Lot 격리 후 재계측',
    ],
    improvement: [
      'Sweep 가속·감속 구간 재설계',
    ],
    logIds: [
      'WD-067',
    ],
    occurrences: 4,
    metrology: 'Post-CMP 광학 두께측정',
    lastSeen: '2026-08-04',
    openCase: true,
    directional: {
      kind: 'layout',
      label: '장비 구조 의존',
    },
  },
  {
    id: 'cmp-scratch-2',
    process: 'CMP',
    pattern: 'Scratch',
    variant: 2,
    name: 'Conditioner/Head-Platen 상대운동 방향으로 인한 방향성 Scratch 불량',
    mechanism: [
      'Head-Platen 상대 속도 방향을 따라 방향성 선형 Scratch 패턴이 발생',
      '상대운동 벡터와 일치하는 방향에 Scratch가 반복되는 불량',
    ],
    waferMap: 'Head-Platen 상대운동 벡터와 일치하는 방향성 선형 Scratch가 Defect Count로 검출되어 불량으로 분류된 형태',
    resolution: [
      'Scratch 방향-상대운동 벡터 대조 분석',
      '고정 방향 반복 검출 Lot 전수 재검사로 심각도 판정',
    ],
    improvement: [
      '회전속도 비 재조정',
    ],
    logIds: [
      'WD-068',
    ],
    occurrences: 5,
    metrology: 'Inspection(DF)',
    lastSeen: '2026-08-05',
    openCase: true,
    directional: {
      kind: 'vector',
      from: 3,
      to: 9,
      label: '3시→9시 방향',
    },
  },
  {
    id: 'cmp-nearfull-2',
    process: 'CMP',
    pattern: 'Near-full',
    variant: 2,
    name: 'Slurry 미공급/Pad Glazing으로 인한 전면 Polishing 불량',
    mechanism: [
      '공급 라인 이상이나 Conditioning 누락으로 웨이퍼 전면의 Polishing이 진행되지 않음',
      'Polishing 미진행으로 Remaining Thickness(THK)가 Spec 대비 거의 그대로 높게 측정되는 불량 발생',
    ],
    waferMap: '전체 영역의 Remaining Thickness(THK)가 Spec보다 커서 불량으로 분류된 형태',
    resolution: [
      'Slurry 미공급 확인 시 즉시 공정 중단',
      '전면 Remaining Thickness(THK) 이상 Lot 전량 격리 후 전수검사',
    ],
    improvement: [
      'Slurry 공급 라인 Interlock',
      'Conditioning 주기 준수',
    ],
    logIds: [
      'WD-069A',
      'WD-069B',
    ],
    occurrences: 4,
    metrology: 'Post-CMP 광학 두께측정',
    lastSeen: '2026-08-05',
    openCase: true,
  },
];

/** 해당 공정이 이 결함유형을 유발하지 않는다고 본 근거 — 빈칸과 "배제됨"은 다르다 */
export const EXCLUSION_NOTES: ExclusionNote[] = [
  {
    process: 'DIFFUSION',
    pattern: 'Center',
    reason: 'Inner/Outer Tube 이중구조·웨이퍼 회전이 원래 중심-외곽 균일화를 위한 설계라 Diffusion이 직접 유발하는 경우는 드묾',
  },
  {
    process: 'PHOTO',
    pattern: 'Donut',
    reason: 'Scanner 노광은 Reticle Field 단위로 진행되기 때문에 웨이퍼 전체에 도넛형 불량을 유발할 가능성 매우 낮음',
  },
  {
    process: 'PHOTO',
    pattern: 'Loc',
    reason: 'Scanner 노광은 Reticle Field 단위로 진행되기 때문에 한 곳에 뭉친 무작위 국소 불량을 유발할 가능성 매우 낮음',
  },
  {
    process: 'CLEANING',
    pattern: 'Center',
    reason: 'Batch Type은 균일하게 용액에 담구는 방식, Single Type도 중심→Edge 영역 스윕이거나 하부→상부 스윕이라 중심부 선택적 결함 유발 확률 드묾',
  },
];
